steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build --build-arg CI_ENVIRONMENT=development --build-arg DATABASE_DEFAULT_DATABASE="$$_DATABASE_DEFAULT_DATABASE" --build-arg DATABASE_DEFAULT_HOSTNAME="$$_DATABASE_DEFAULT_HOSTNAME" --build-arg DATABASE_DEFAULT_PASSWORD="$$_DATABASE_DEFAULT_PASSWORD" --build-arg DATABASE_DEFAULT_USERNAME="$$_DATABASE_DEFAULT_USERNAME" --build-arg DATABASE_DEFAULT_DBDRIVER="$$_DATABASE_DEFAULT_DBDRIVER" --build-arg DATABASE_DEFAULT_DBPREFIX="$$_DATABASE_DEFAULT_DBPREFIX" --build-arg DATABASE_DEFAULT_DBPORT="$$_DATABASE_DEFAULT_DBPORT" -f Dockerfile -t gcr.io/$PROJECT_ID/app-pelepasan-image:latest .

  secretEnv: [
    '_DATABASE_DEFAULT_HOSTNAME',
    '_DATABASE_DEFAULT_DATABASE',
    '_DATABASE_DEFAULT_USERNAME',
    '_DATABASE_DEFAULT_PASSWORD',
    '_DATABASE_DEFAULT_DBDRIVER',
    '_DATABASE_DEFAULT_DBPREFIX',
    '_DATABASE_DEFAULT_DBPORT'
  ]
  env:
    - 'CI_ENVIRONMENT=development'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_HOSTNAME/versions/latest'
      env: '_DATABASE_DEFAULT_HOSTNAME'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_DATABASE/versions/latest'
      env: '_DATABASE_DEFAULT_DATABASE'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_USERNAME/versions/latest'
      env: '_DATABASE_DEFAULT_USERNAME'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_PASSWORD/versions/latest'
      env: '_DATABASE_DEFAULT_PASSWORD'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_DBDRIVER/versions/latest'
      env: '_DATABASE_DEFAULT_DBDRIVER'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_DBPREFIX/versions/latest'
      env: '_DATABASE_DEFAULT_DBPREFIX'
    - versionName: 'projects/$PROJECT_NUMBER/secrets/DATABASE_DEFAULT_DBPORT/versions/latest'
      env: '_DATABASE_DEFAULT_DBPORT'
  